
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jul  2 2025 15:36:45 IST (Jul  2 2025 10:06:45 UTC)

// Verification Directory fv/mux8_1 

module mux8_1(x, s, y);
  input [7:0] x;
  input [2:0] s;
  output y;
  wire [7:0] x;
  wire [2:0] s;
  wire y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  OAI31X1 g365__2398(.A0 (s[2]), .A1 (s[0]), .A2 (n_3), .B0 (n_7), .Y
       (y));
  AOI211XL g366__5107(.A0 (s[0]), .A1 (n_5), .B0 (n_4), .C0 (n_6), .Y
       (n_7));
  AND3XL g367__6260(.A (s[2]), .B (s[0]), .C (n_0), .Y (n_6));
  NOR2XL g369__4319(.A (s[2]), .B (n_1), .Y (n_5));
  NOR3BXL g368__8428(.AN (s[2]), .B (n_2), .C (s[0]), .Y (n_4));
  MXI2XL g372__5526(.A (x[4]), .B (x[6]), .S0 (s[1]), .Y (n_3));
  MXI2XL g373__6783(.A (x[0]), .B (x[2]), .S0 (s[1]), .Y (n_2));
  MXI2XL g370__3680(.A (x[5]), .B (x[7]), .S0 (s[1]), .Y (n_1));
  MX2XL g371__1617(.A (x[1]), .B (x[3]), .S0 (s[1]), .Y (n_0));
endmodule

